trigger:
- main
pool: 
  vmImage: ubuntu-latest
variables:
  buildConfiguration: 'Release'
steps:
- bash: echo Start build
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'